#tratamentos de erros
try:
    a = 1200 / 0
except:
    print('DIVISAO POR ZERO, NAO DA PRA FAZER')

print('* aaaaa *')

'''except Exception as err: movendo o erro p uma variavel
    print('ACONTECEU ALGUM ERRO: ', err)'''
